services:
  db:
    image: bitnami/mysql:latest
    networks:
      net_pamedic:
        aliases:
          - db
    volumes:
      - db:/bitnami/mysql/data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 10s
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=pamedic
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      net_pamedic:
    depends_on:
      - db
    ports:
      - 9090:80
  laravel:
    image: felipe89/pamedic-php8.1:latest
    networks:
      net_pamedic:
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/var/www/html
      - ./storage/logs:/var/logs
      - vendor:/var/www/html/vendor
      - composer_cache:/tmp/composer
    ports:
      - 8000:80
    command: >
      sh -c 'composer install
      && rm -Rf public/storage || true && php artisan storage:link
      && php artisan serve --host=0.0.0.0 --port=80'
volumes:
  db:
  vendor:
  composer_cache:

networks:
  net_pamedic:
