FROM php:8.2-apache

ENV DEBIAN_FRONTEND=noninteractive


RUN apt-get update && apt-get install -y \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    git \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY . /var/www/html

RUN a2enmod rewrite

EXPOSE 80

WORKDIR /var/www/html

CMD ["apache2-foreground"]
